use_frameworks!

target 'WJBaseComponent_Example' do
  pod 'WJBaseComponent', :path => '../'

  target 'WJBaseComponent_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
